version = 1

exclude_patterns = ["docs/**"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
    "requirements/pip.txt",
    "requirements/testing.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["dockerfiles/Dockerfile"]
